---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: centos8
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp:exec,mode=777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp:exec,mode=777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: True
  options:
    vvv: True
  ansible_args:
    - -vvv
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint .
  ansible-lint .
