---
- name: Check that necessary variables are defined
  assert:
    that:
      - installer_scenario is defined

- name: 'Run installer'
  command: >
    {{ installer_command }}
    --scenario {{ installer_scenario }}
    {{ (installer_verbose|bool) | ternary("-v", "") }}
    {{ (installer_no_colors|bool) | ternary("--no-colors", "") }}
    {{ installer_options | join(' ') }}
    --detailed-exitcodes
  register: installer_run
  changed_when: installer_run.rc == 2
  failed_when: installer_run.rc not in [0, 2]
