---
- name: 'Install centos-release-scl-rh'  # noqa package-latest
  yum:
    name: centos-release-scl-rh
    state: latest
    update_cache: true
  tags:
    - packages
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: 'Setup Foreman {{ foreman_repositories_version }} Repository'
  yum:
    name: https://yum.theforeman.org/releases/{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
    disable_gpg_check: true
    state: present
  tags:
    - packages

- name: 'Setup Katello {{ foreman_repositories_katello_version }} Repository'
  yum:
    name: https://yum.theforeman.org/katello/{{ foreman_repositories_katello_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/katello-repos-latest.rpm
    disable_gpg_check: true
    state: present
  when: foreman_repositories_katello_version is defined
